version: "3.7"
services:
  db:
    image: postgres:latest
    env_file: envs/dev.env
    ports:
      - 5431:5431
    command: -p 5431

  migration:
    build: .
    env_file: envs/dev.env
    command: bash -c 'while !</dev/tcp/db/5431; do sleep 1; done; python manage.py makemigrations; python manage.py migrate'

    stdin_open: true
    tty: true

    depends_on:
      - db

  web:
    build: .
    env_file: envs/dev.env
    command: bash -c 'while !</dev/tcp/db/5431; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'

    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/code

    depends_on:
      - db
      - migration

volumes:
  db_kenzie_starter:
    external: true
