# Generated by Django 3.1 on 2021-06-15 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('country_full', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('localized_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kenzie_starter_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('backers', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('deadline', models.DateField()),
                ('goal', models.FloatField()),
                ('pledged', models.FloatField()),
                ('usd_pledged', models.FloatField()),
                ('currency', models.CharField(max_length=255)),
                ('launched_at', models.DateTimeField()),
                ('state', models.CharField(max_length=255)),
                ('state_changed_at', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kenzie_starter_app.creator')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kenzie_starter_app.location')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kenzie_starter_app.subcategory')),
            ],
        ),
    ]
