# Generated by Django 3.1 on 2021-06-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenzie_starter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.TextField(choices=[('failed', 'Failed'), ('live', 'Live'), ('canceled', 'Canceled'), ('successful', 'Successful')]),
        ),
    ]
