# Generated by Django 3.1 on 2021-06-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kenzie_starter_app', '0005_auto_20210617_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='kenzie_star_name_499018_idx',
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='kenzie_star_name_4b0ea2_idx'),
        ),
    ]
