# Generated by Django 3.1 on 2021-06-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kenzie_starter_app', '0006_auto_20210617_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='kenzie_star_name_4b0ea2_idx',
        ),
    ]
